import {
  Project,
  FurnitureItem,
  PricingPlan,
  Testimonial,
  DashboardStats,
} from "./types";

export const dashboardStats: DashboardStats = {
  totalProjects: 48,
  activeProjects: 12,
  completedProjects: 36,
  totalRevenue: 284500000,
  clientSatisfaction: 4.8,
};

export const projects: Project[] = [
  {
    id: "1",
    name: "강남 펜트하우스 리모델링",
    clientName: "김민수",
    status: "in_progress",
    roomType: "거실",
    style: "모던 미니멀",
    budget: 85000000,
    thumbnail: "",
    createdAt: "2026-01-15",
    updatedAt: "2026-02-10",
    progress: 65,
  },
  {
    id: "2",
    name: "서초 오피스텔 인테리어",
    clientName: "이서연",
    status: "planning",
    roomType: "원룸",
    style: "스칸디나비안",
    budget: 25000000,
    thumbnail: "",
    createdAt: "2026-02-01",
    updatedAt: "2026-02-08",
    progress: 15,
  },
  {
    id: "3",
    name: "판교 카페 인테리어",
    clientName: "박지훈",
    status: "review",
    roomType: "상업공간",
    style: "인더스트리얼",
    budget: 120000000,
    thumbnail: "",
    createdAt: "2025-12-20",
    updatedAt: "2026-02-05",
    progress: 90,
  },
  {
    id: "4",
    name: "한남동 타운하우스",
    clientName: "정유진",
    status: "completed",
    roomType: "전체",
    style: "모던 클래식",
    budget: 200000000,
    thumbnail: "",
    createdAt: "2025-10-01",
    updatedAt: "2026-01-20",
    progress: 100,
  },
  {
    id: "5",
    name: "용산 신축 아파트",
    clientName: "최현우",
    status: "in_progress",
    roomType: "주방",
    style: "모던",
    budget: 45000000,
    thumbnail: "",
    createdAt: "2026-01-20",
    updatedAt: "2026-02-11",
    progress: 40,
  },
  {
    id: "6",
    name: "성수동 공유오피스",
    clientName: "김태희",
    status: "planning",
    roomType: "오피스",
    style: "미니멀",
    budget: 95000000,
    thumbnail: "",
    createdAt: "2026-02-05",
    updatedAt: "2026-02-10",
    progress: 10,
  },
];

export const furnitureItems: FurnitureItem[] = [
  {
    id: "f1",
    name: "모던 패브릭 소파 3인용",
    category: "소파",
    brand: "리빙하우스",
    price: 1890000,
    dimensions: { width: 220, height: 85, depth: 95 },
    color: "그레이",
    material: "패브릭",
    image: "",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "f2",
    name: "원목 다이닝 테이블 6인용",
    category: "테이블",
    brand: "까사미아",
    price: 2450000,
    dimensions: { width: 180, height: 75, depth: 90 },
    color: "월넛",
    material: "원목",
    image: "",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "f3",
    name: "LED 플로어 스탠드",
    category: "조명",
    brand: "루미나",
    price: 389000,
    dimensions: { width: 35, height: 165, depth: 35 },
    color: "블랙",
    material: "메탈",
    image: "",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "f4",
    name: "월넛 TV 콘솔",
    category: "수납",
    brand: "한샘",
    price: 1290000,
    dimensions: { width: 200, height: 55, depth: 45 },
    color: "월넛",
    material: "MDF + 원목",
    image: "",
    rating: 4.6,
    inStock: false,
  },
  {
    id: "f5",
    name: "벨벳 라운지 체어",
    category: "의자",
    brand: "이케아",
    price: 699000,
    dimensions: { width: 72, height: 100, depth: 78 },
    color: "네이비",
    material: "벨벳",
    image: "",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "f6",
    name: "대리석 커피 테이블",
    category: "테이블",
    brand: "보떼메종",
    price: 1590000,
    dimensions: { width: 120, height: 40, depth: 60 },
    color: "화이트",
    material: "대리석 + 메탈",
    image: "",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "f7",
    name: "북유럽 펜던트 조명",
    category: "조명",
    brand: "루이스폴센",
    price: 850000,
    dimensions: { width: 50, height: 30, depth: 50 },
    color: "화이트",
    material: "알루미늄",
    image: "",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "f8",
    name: "모듈형 수납장",
    category: "수납",
    brand: "무인양품",
    price: 450000,
    dimensions: { width: 80, height: 200, depth: 40 },
    color: "내추럴",
    material: "파인우드",
    image: "",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "f9",
    name: "킹사이즈 프레임 침대",
    category: "침대",
    brand: "시몬스",
    price: 3200000,
    dimensions: { width: 200, height: 110, depth: 210 },
    color: "그레이",
    material: "패브릭 + 원목",
    image: "",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "f10",
    name: "라탄 사이드 테이블",
    category: "테이블",
    brand: "자라홈",
    price: 259000,
    dimensions: { width: 45, height: 55, depth: 45 },
    color: "내추럴",
    material: "라탄",
    image: "",
    rating: 4.2,
    inStock: true,
  },
  {
    id: "f11",
    name: "아트 월 선반",
    category: "수납",
    brand: "이케아",
    price: 89000,
    dimensions: { width: 110, height: 26, depth: 20 },
    color: "블랙",
    material: "메탈",
    image: "",
    rating: 4.1,
    inStock: true,
  },
  {
    id: "f12",
    name: "세라믹 화병 세트",
    category: "소품",
    brand: "자라홈",
    price: 129000,
    dimensions: { width: 15, height: 30, depth: 15 },
    color: "화이트",
    material: "세라믹",
    image: "",
    rating: 4.6,
    inStock: true,
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: "starter",
    name: "스타터",
    price: 49000,
    period: "월",
    description: "개인 디자이너를 위한 시작 플랜",
    features: [
      "프로젝트 5개",
      "2D 룸 디자이너",
      "기본 가구 카탈로그",
      "무드보드 3개",
      "이메일 지원",
    ],
    highlighted: false,
  },
  {
    id: "professional",
    name: "프로페셔널",
    price: 129000,
    period: "월",
    description: "전문 디자이너와 소규모 스튜디오",
    features: [
      "프로젝트 무제한",
      "3D 룸 디자이너",
      "프리미엄 가구 카탈로그",
      "무드보드 무제한",
      "고객 공유 포털",
      "우선 지원",
      "견적서 자동 생성",
    ],
    highlighted: true,
  },
  {
    id: "enterprise",
    name: "엔터프라이즈",
    price: 349000,
    period: "월",
    description: "대형 디자인 스튜디오와 기업",
    features: [
      "프로페셔널 전체 기능",
      "팀 협업 (최대 20명)",
      "브랜드 커스터마이징",
      "API 연동",
      "전담 매니저",
      "SLA 보장",
      "교육 및 온보딩",
      "맞춤형 리포트",
    ],
    highlighted: false,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "김소현",
    role: "대표 디자이너",
    company: "소현 인테리어 스튜디오",
    content:
      "클라이언트에게 디자인 안을 보여줄 때 룸 디자이너 기능이 정말 유용해요. 프로젝트 관리까지 한 곳에서 할 수 있어서 업무 효율이 크게 올랐습니다.",
    avatar: "",
    rating: 5,
  },
  {
    id: "t2",
    name: "박정우",
    role: "실장",
    company: "모던리빙 디자인",
    content:
      "가구 카탈로그가 잘 정리되어 있고, 견적서 자동 생성 기능 덕분에 행정 업무 시간이 절반으로 줄었어요. 강력 추천합니다.",
    avatar: "",
    rating: 5,
  },
  {
    id: "t3",
    name: "이하은",
    role: "프리랜서 디자이너",
    company: "",
    content:
      "무드보드 기능이 특히 마음에 들어요. 영감을 정리하고 클라이언트와 공유하기가 너무 편해졌습니다. 가격 대비 기능이 훌륭해요.",
    avatar: "",
    rating: 4,
  },
  {
    id: "t4",
    name: "장민호",
    role: "CEO",
    company: "스페이스랩",
    content:
      "팀 협업 기능 덕분에 여러 프로젝트를 동시에 관리할 수 있게 되었어요. 대시보드에서 전체 현황을 한눈에 파악할 수 있어 좋습니다.",
    avatar: "",
    rating: 5,
  },
];

export const roomStyles = [
  "모던 미니멀",
  "스칸디나비안",
  "인더스트리얼",
  "모던 클래식",
  "미드센추리 모던",
  "재패니즈 모던",
  "보헤미안",
  "코스탈",
  "트래디셔널",
  "컨템포러리",
];

export const roomTypes = [
  "거실",
  "침실",
  "주방",
  "욕실",
  "서재",
  "원룸",
  "오피스",
  "상업공간",
  "전체",
];

export const furnitureCategories = [
  "전체",
  "소파",
  "테이블",
  "의자",
  "침대",
  "수납",
  "조명",
  "소품",
];
